src/components/App.jsx
src/components/Homepage/DescSection/DescSection.js
src/components/Homepage/DescSection/DescSection.module.css

Section component

---

src/components/Homepage/DescSection/DescSection.module.css
src/pages/Homepage.js

created home page

---

src/components/Homepage/HeroSection/HeroSection.js
src/components/Homepage/HeroSection/HeroSection.module.css

font, space bug fixes. Link for navigation is added.

Home page bug fixes

---

src/components/Homepage/DescSection/DescSection.module.css
src/components/Homepage/ReviewsSection/ReviewsSection.js
src/components/Homepage/ReviewsSection/ReviewsSection.module.css
src/pages/Homepage.js

Added reviews slider to hp

---

src/components/Button/BtnBackHome/BtnBackHome.js
src/components/Button/BtnBackHome/BtnBackHome.module.css

add button BtnBackHome component 404 page

---

src/components/User/ThemeToggler/ThemeToggler.js

Save user theme on server if changed

save theme

---

src/components/Homepage/ReviewsSection/ReviewsSection.js

Connected slider to Redux, but it doesn't work. No console errors.

Reviews backend data

---

src/pages/StatisticsPage/StatisticsPage.js

Added statistics elements to the page

added statistics and dropdown calendar

---

src/css/variables.css
src/pages/NotFoundPage/NotFoundPage.js
src/pages/NotFoundPage/NotFoundPage.module.css

update color var for theme

---

src/components/User/Header/Header.js
src/components/User/MainLayout/MainLayout.js
src/components/User/Sidebar/Sidebar.js

add toggleSidebar

---

src/components/User/ThemeToggler/ThemeToggler.js

fix theme toggle

---

src/components/User/CalendarPopup/CalendarPopup.js
src/components/User/CalendarPopup/CalendarPopup.module.css

Added styles to dropdown calendar.

Calendar dropdown styles

---

src/components/User/MainLayout/MainLayout.js
src/components/User/ThemeToggler/ThemeToggler.js

fix main-layout

---

src/components/User/CalendarToolbar/PeriodTypeSelect/PeriodTypeSelect.js
src/components/User/CalendarToolbar/PeriodTypeSelect/PeriodTypeSelect.module.css
src/css/variables.css
src/pages/NotFoundPage/NotFoundPage.js

PeriodTypeSelect + fix NotFoundPage theme

PeriodTypeSelect + fix NotFoundPage theme

---

src/components/User/Header/Header.module.css

Трошки пофіксив бургер, ще чуть пізніше додам зміни для тайтла

Melnychuk store

---

src/components/User/CalendarPopup/CalendarPopup.module.css
src/components/User/CalendarToolbar/PeriodPaginator/PeriodPaginator.js
src/components/User/CalendarToolbar/PeriodPaginator/PeriodPaginator.module.css
src/components/User/CalendarToolbar/PeriodTypeSelect/PeriodTypeSelect.module.css
src/css/variables.css
src/pages/StatisticsPage/StatisticPage.module.css
src/pages/StatisticsPage/StatisticsPage.js

add calendarToolbar styles and fix css

add calendarToolbar styles and fix css

---

src/components/User/ColumnHeadBar/ColumnHeadBar.jsx
src/components/User/ColumnHeadBar/ColumnHeadBar.module.css
src/components/User/TaskColumnCard/TaskColumnCard.module.css
src/components/User/TaskSwitcher/TaskSwitcher.module.css
src/components/User/TaskToolbar/TaskToolbar.module.css

Add right styles for text in ChosenDay

Chosen day/fix styles

---

src/components/User/MainLayout/MainLayout.js
src/pages/StatisticsPage/StatisticPage.module.css

add useState(false) for sideBar + fix style calendarToolbar

add useState(false) for sideBar

---

src/components/Calendar/СalendarTable/СalendarTable.jsx

Привіт виправлена помилка показу активної дати

fix error 3

---

src/components/User/Header/Header.module.css

fix css burgerButton, burgerIcon

fix css burgerButton, burgerIcon

---

src/components/Calendar/СalendarTable/СalendarTable.jsx

Поправив задвоєння відображення тасків в наступному році в календарі

fix errors

---

src/components/User/Sidebar/UserNav/UserNav.module.css

fix text color nav item Sidebar

fix text color nav item Sidebar

---

src/components/Popup/Popup.jsx
src/components/Popup/Popup.module.css

fix icon, fix responsive, fix backdrop click and esc press,

fix bug with modal

---

src/components/Homepage/HeroSection/HeroSection.module.css

fixed height

---

src/components/UserForm/UserForm.jsx

fix avatar

---

src/components/User/ColumnTasksList/ColumnTasksList.jsx
src/components/User/TaskColumnCard/TaskColumnCard.jsx
src/components/User/TaskColumnCard/TaskColumnCard.module.css
src/components/User/TaskSwitcher/TaskSwitcher.js
src/components/User/TaskSwitcher/TaskSwitcher.module.css
src/components/User/TaskToolbar/TaskToolbar.jsx
src/components/User/TasksColumn/TasksColumn.module.css
src/components/User/TasksColumnsList/TasksColumnsList.jsx

Fix position absolute for taskswitcher
